// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace ETicaretweb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "67CD3F79C3A2B26A5F2BFDF1610E31452DB4FD4F60381CB317FF5C6F5E996DEF",
                            Role = "Admin",
                            Username = "Devran"
                        });
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CategoryName = "Telefon",
                            ImageUrl = "telefon.webp",
                            URL = "akilli-telefon"
                        },
                        new
                        {
                            id = 2,
                            CategoryName = "Kıyafetler",
                            ImageUrl = "kiyafet.webp",
                            URL = "kiyafet"
                        },
                        new
                        {
                            id = 3,
                            CategoryName = "Aksesuar",
                            ImageUrl = "aksesuar.jpg",
                            URL = "aksesuar"
                        });
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CategoryId = 1,
                            Price = 45000,
                            ProductName = "İphone15",
                            URL = "iphone15",
                            isActive = true,
                            quantity = 1
                        },
                        new
                        {
                            id = 2,
                            CategoryId = 1,
                            Price = 55000,
                            ProductName = "İphone16",
                            URL = "iphone16",
                            isActive = true,
                            quantity = 1
                        },
                        new
                        {
                            id = 3,
                            CategoryId = 1,
                            Price = 40000,
                            ProductName = "Samsung Galaxy S24",
                            URL = "samsung-s24",
                            isActive = true,
                            quantity = 1
                        });
                });

            modelBuilder.Entity("Models.ProductImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("productImages");

                    b.HasData(
                        new
                        {
                            id = 1,
                            ProductId = 1,
                            Url = "/images/iphone15.jpg"
                        },
                        new
                        {
                            id = 2,
                            ProductId = 2,
                            Url = "/images/iphone16.jpg"
                        },
                        new
                        {
                            id = 3,
                            ProductId = 3,
                            Url = "/images/samsung-s24.jpg"
                        });
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.HasOne("Models.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Models.ProductImage", b =>
                {
                    b.HasOne("Models.Product", "Product")
                        .WithOne("ProductImage")
                        .HasForeignKey("Models.ProductImage", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.Navigation("ProductImage");
                });
#pragma warning restore 612, 618
        }
    }
}
